name: parking-garage-ecossystem

services:
  mysql:
    image: mysql:9.6.0
    container_name: parking_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parking_garage
      MYSQL_USER: parking
      MYSQL_PASSWORD: parking
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  simulator:
    image: cfontes0estapar/garage-sim:1.0.0
    container_name: parking_simulator
    network_mode: "host"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://127.0.0.1:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  parking-garage:
    image: maven:3.9.14-eclipse-temurin-21
    container_name: parking_api
    network_mode: "host"
    working_dir: /app
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    command: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    environment:
      DB_URL: jdbc:mysql://127.0.0.1:3306/parking_garage?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: parking
      DB_PASSWORD: parking
      SIMULATOR_URL: http://127.0.0.1:3000
      PARKING_PRICING_FACTOR_DISCOUNT: "0.90"
      PARKING_PRICING_FACTOR_NORMAL: "1.00"
      PARKING_PRICING_FACTOR_PLUS_STEP1: "1.10"
      PARKING_PRICING_FACTOR_PLUS_STEP2: "1.25"
      PARKING_PRICING_TOLERANCE_MINUTES: "30"
    depends_on:
      mysql:
        condition: service_healthy
      simulator:
        condition: service_started

volumes:
  mysql_data:
  maven_cache:
