name: parking-garage

services:
  mysql:
    image: mysql:8.4
    container_name: parking-garage-mysql
    environment:
      MYSQL_DATABASE: parking_garage
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: parking
      MYSQL_PASSWORD: parking
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uparking",
          "-pparking",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
